ARG UBUNTU_VERSION=22.04

FROM rust:1.89-bookworm AS envd-builder

WORKDIR /src
COPY cube-envd/ ./cube-envd/

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/src/cube-envd/target \
    cd cube-envd \
    && cargo build --release \
    && mkdir -p /out \
    && install -m 0755 target/release/cube-envd /out/envd \
    && /out/envd -version \
    && /out/envd -commit

FROM ubuntu:${UBUNTU_VERSION}

ARG ENVD_IMPL=cube-envd

ENV ENVD_IMPL=${ENVD_IMPL} \
    ENVD_PORT=49983 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        sudo \
        tini \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --uid 1000 --shell /bin/bash user \
    && echo 'user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user

COPY --from=envd-builder /out/envd /usr/bin/envd
COPY docker/cube-entrypoint.sh /usr/local/bin/cube-entrypoint.sh

RUN chmod +x /usr/bin/envd /usr/local/bin/cube-entrypoint.sh \
    && mkdir -p /var/log \
    && /usr/bin/envd -version \
    && /usr/bin/envd -commit

LABEL org.opencontainers.image.source="https://github.com/TencentCloud/CubeSandbox" \
      org.opencontainers.image.title="cubesandbox-base" \
      org.opencontainers.image.description="CubeSandbox base image with cube-envd" \
      org.opencontainers.image.licenses="Apache-2.0" \
      io.cubesandbox.envd.impl="cube-envd-rust"

EXPOSE 49983

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/cube-entrypoint.sh"]
CMD []
